version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "TUC:GR8?MHYP"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQ_DBNAME: "MYDATABASE"      
    volumes:
      - ./sqlserver_data:/var/opt/mssql/data
    ports:
      - "1433:1433"